### ISSUE TITLE
Android Application crash

### ISSUE THREAD

**Issue by chancezeus** [spoonconsulting/cordova-plugin-background-upload#126] opened 2020-12-04 18:33 UTC
I have been trying to get this plugin working and after some trail end error I finally managed to get it to start (using the v2-0-0 branch, other branches either simply didn't work or gave random errors during plugin add and/or compile), however now the following problem occurs and the application crashes completely

```
12-04 18:59:36.680  1441  1441 E AndroidRuntime: java.lang.RuntimeException: Unable to create service net.gotev.uploadservice.UploadService: java.lang.IllegalArgumentException: You have to set namespace to your app package name (context.packageName) in your Application subclass
12-04 18:59:36.680  1441  1441 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4166)
12-04 18:59:36.680  1441  1441 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:268)
12-04 18:59:36.680  1441  1441 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1998)
12-04 18:59:36.680  1441  1441 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-04 18:59:36.680  1441  1441 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
12-04 18:59:36.680  1441  1441 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7814)
12-04 18:59:36.680  1441  1441 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-04 18:59:36.680  1441  1441 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-04 18:59:36.680  1441  1441 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
12-04 18:59:36.680  1441  1441 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: You have to set namespace to your app package name (context.packageName) in your Application subclass
12-04 18:59:36.680  1441  1441 E AndroidRuntime: 	at net.gotev.uploadservice.UploadServiceConfig.getNamespace(UploadServiceConfig.kt:74)
12-04 18:59:36.680  1441  1441 E AndroidRuntime: 	at net.gotev.uploadservice.UploadServiceConfig.getBroadcastNotificationAction(UploadServiceConfig.kt:234)
12-04 18:59:36.680  1441  1441 E AndroidRuntime: 	at net.gotev.uploadservice.UploadServiceConfig.getBroadcastNotificationActionIntentFilter(UploadServiceConfig.kt:248)
12-04 18:59:36.680  1441  1441 E AndroidRuntime: 	at net.gotev.uploadservice.observer.request.NotificationActionsObserver.register(NotificationActionsObserver.kt:31)
12-04 18:59:36.680  1441  1441 E AndroidRuntime: 	at net.gotev.uploadservice.UploadService.onCreate(UploadService.kt:193)
12-04 18:59:36.680  1441  1441 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4154)
12-04 18:59:36.680  1441  1441 E AndroidRuntime: 	... 8 more
```

From the docs of the relevant package "net.gotev:uploadservice" it seems to expect that the configuration for the UploadService is set from the Application "onCreate" method (see https://github.com/gotev/android-upload-service/wiki/Getting-Started-with-4.x) but instead it's being called late (in the "initManager" method of the "FileTransferPlugin" class) and I suspect this being the cause. Since the plugin already sets it's own application class (com.orm.SugarApp), wouldn't it be wise to instead create a custom application class that extends the "com.orm.SugarApp" class and adds the relevant functionality to the onCreate method there (thus preventing the crash you see above)...

**Comment by ombr** [comment] 2020-12-10 14:28
Hi @chancezeus,

You are right, we will try to fix this but meanwhile you are more than welcome to send us a pull request ;-)

Thanks.

Luc

**Comment by azharbeebeejaun** [comment] 2021-04-21 11:48
Hi @chancezeus,

I'm late but did you manage to get a fix for this error?
Were you able to reproduce this every time? On what device/emulator was it?

**Comment by chancezeus** [comment] 2021-04-23 12:02
It happened all the time if the application was closed with one or more uploads queued and it was on every device/emulator I tested it with.

I have not managed yet to get a (clean enough) fix for the issue, but it should be as simple as creating a custom application class which in turn extends the "com.orm.SugarApp" application class and add the required config in onCreate of that app instead of waiting till the plugin gets initialized, just check the documentation for the uploadservice library I linked in the original post.

**Comment by azharbeebeejaun** [comment] 2021-04-23 12:21
Was it online or offline? I'm not able to reproduce this at all but can see some devices having crashes. Could you provide like a video or something if possible please ? Or even, some steps you're fairly sure will help reproduce this error.

Thanks a lot.

**Closed** 2022-06-08 07:55 UTC
